[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "W", "F", "I", "S", "C90", "B", "UP", "ANN", "N"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S", "ANN", "N"]

[tool.pytest.ini_options]
pythonpath = ["src/"]
testpaths = "tests"

[tool.mypy]
exclude = ["tests", "build"]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
namespace_packages = true
warn_redundant_casts = true
warn_unused_ignores = true


[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cactus_schema"
description = "Public facing models for the various CACTUS APIs"
keywords = ["CSIP-AUS", "CACTUS", "schema", "models"]
requires-python = ">=3.12"
dynamic = ["version", "readme"]
dependencies = ["cactus_test_definitions>=1.9.0", "dataclass-wizard>=0.35.0,<1"]
authors = [
    { name = "Mike Turner", email = "mike.turner@anu.edu.au" },
    { name = "Josh Vote", email = "joshua.vote@anu.edu.au" },
    { name = "Lachlan Watson", email = "lachlan.watson@anu.edu.au" },
]
maintainers = [
    { name = "Mike Turner", email = "mike.turner@anu.edu.au" },
    { name = "Josh Vote", email = "joshua.vote@anu.edu.au" },
    { name = "Lachlan Watson", email = "lachlan.watson@anu.edu.au" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development",
    "Typing :: Typed",
]

[tool.setuptools.dynamic]
version = { attr = "cactus_schema.__version__" }
readme = { file = ["README.md"], content-type = "text/markdown" }

[project.optional-dependencies]
dev = ["coverage", "mypy", "ruff"]
test = ["pytest", "assertical"]

[tool.setuptools.package-data]
"cactus_schema" = ["py.typed"]
